var shuffleSequence =  seq('agreement', 'instr',"practice", randomize(shuffle(startsWith('2'))),"quest","sr","code")

var showProgressBar = false;

var pageTitle= "P2BA";

function generateRandomNumber(){
    var num = Math.floor(Math.random()*54+40);
    var myArray = ['Y', 'F', 'W'];
    var rand = myArray[Math.floor(Math.random() * myArray.length)];
    var myArray2 = ['A', 'W', 'R', 'U'];
    var rand2 = myArray2[Math.floor(Math.random() * myArray2.length)];
    var myArray3 = ['Q', 'E', 'L', 'T'];
    var rand3 = myArray3[Math.floor(Math.random() * myArray3.length)];
    var num2 = Math.floor(Math.random()*4+1);

    var n = String(rand)+String(num)+String(rand3)+String(num2)+String(rand2);

return n;
}

var manualSendResults = true;
var defaults = [
    "Question", {hasCorrect: true},
    "Message", {hideProgressBar: true},
    "Sentence", {hideProgressBar: true, transfer: 1500},
    "Form", {hideProgressBar: true,continueOnReturn: true,saveReactionTime: false},
    "NewForm", {hideProgressBar: true,continueOnReturn: true,saveReactionTime: false},
    "PictureAccept", {presentAsScale: true,hideProgressBar: true},
    "SubHtmlFlash", {presentAsScale: true, presentHorizontally: false, as: ["True", "False"]},
    "Code", {hideProgressBar: true,transfer: null}];


var items = [
    ['agreement', "NewForm", {html: {include: 'agreement_EN.html'}}],
    ['instr',"NewMessage", {html: {include: 'instructions.html'}}],

    ['practice', "Sentence", {html: "<center>Some dots are blue.</center> <br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},
     "SubHtmlFlash", {html:"<center>Some dots are blue.</center> <br> <center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_A_dots_blue_square_below_.png' border='2'></center>", q:"Practice"}],
   ['2_BA_Target1_True_B_Baseline_4-8_are',"Sentence",{html: "<center>All letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_blue_.png'border='2'></center> ",q:'All letters are blue.'}] ,
['2_BA_Target1_False_B_Baseline_5-9_are',"Sentence",{html: "<center>All letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_green_.png'border='2'></center> ",q:'All letters are blue.'}] ,
['2_BA_Target1_True_B_Baseline_4-8_are',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_green_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Target1_False_B_Baseline_5-9_are',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_blue_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Filler-Target1_False_B_Baseline_X-X_X',"Sentence",{html: "<center>All letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_green_.png'border='2'></center> ",q:'All letters are blue.'}] ,
['2_BA_Filler-Target1_False_B_Baseline_X-X_X',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_blue_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Target1_True_B_Baseline_4-8_are',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_green_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Target1_False_B_Baseline_5-9_are',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_red_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Target1_True_B_Baseline_4-8_are',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_green_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Target1_False_B_Baseline_5-9_are',"Sentence",{html: "<center>All letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_red_.png'border='2'></center> ",q:'All letters are blue.'}] ,
['2_BA_Filler-Target1_False_B_Baseline_X-X_X',"Sentence",{html: "<center>All letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_green_.png'border='2'></center> ",q:'All letters are blue.'}] ,
['2_BA_Filler-Target1_True_B_Baseline_X-X_X',"Sentence",{html: "<center>All letters are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_dots_red_.png'border='2'></center> ",q:'All letters are red.'}] ,
['2_BA_Target1_True_B_Baseline_4-8_are',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_green_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Target1_False_B_Baseline_5-9_are',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_blue_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Target1_True_B_Baseline_4-8_are',"Sentence",{html: "<center>All letters are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_red_.png'border='2'></center> ",q:'All letters are red.'}] ,
['2_BA_Target1_False_B_Baseline_5-9_are',"Sentence",{html: "<center>All letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_green_.png'border='2'></center> ",q:'All letters are blue.'}] ,
['2_BA_Filler-Target1_True_A_Baseline_X-X_X',"Sentence",{html: "<center>All crosses are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All crosses are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_red_triangle_below_.png'border='2'></center> ",q:'All crosses are red.'}] ,
['2_BA_Filler-Target1_True_A_Baseline_X-X_X',"Sentence",{html: "<center>All crosses are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All crosses are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_green_square_above_.png'border='2'></center> ",q:'All crosses are green.'}] ,
['2_BA_Target1_True_B_Baseline_4-8_are',"Sentence",{html: "<center>All letters are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_red_.png'border='2'></center> ",q:'All letters are red.'}] ,
['2_BA_Target1_False_B_Baseline_5-9_are',"Sentence",{html: "<center>All letters are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_green_.png'border='2'></center> ",q:'All letters are red.'}] ,
['2_BA_Target1_True_B_Baseline_4-8_are',"Sentence",{html: "<center>All letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_blue_.png'border='2'></center> ",q:'All letters are blue.'}] ,
['2_BA_Target1_False_B_Baseline_5-9_are',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_red_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Filler-Target1_True_A_Baseline_X-X_X',"Sentence",{html: "<center>All crosses are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All crosses are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_blue_triangle_above_.png'border='2'></center> ",q:'All crosses are blue.'}] ,
['2_BA_Filler-Target1_False_A_Baseline_X-X_X',"Sentence",{html: "<center>All crosses are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All crosses are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_red_square_above_.png'border='2'></center> ",q:'All crosses are green.'}] ,
['2_BA_Target2_Target_A_Distributive_4-8_are above the line',"Sentence",{html: "<center>Between 4 and 8 dots are above the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 8 dots are above the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_blue_triangle_above_.png'border='2'></center> ",q:'Between 4 and 8 dots are above the line.'}] ,
['2_BA_Target2_Target_A_Distributive_5-9_are below the line',"Sentence",{html: "<center>Between 5 and 9 dots are below the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are below the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_blue_square_below_.png'border='2'></center> ",q:'Between 5 and 9 dots are below the line.'}] ,
['2_BA_Target2_Target_A_Distributive_4-8_are above the line',"Sentence",{html: "<center>Between 4 and 8 dots are above the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 8 dots are above the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_green_triangle_above_.png'border='2'></center> ",q:'Between 4 and 8 dots are above the line.'}] ,
['2_BA_Target2_Target_A_Distributive_5-9_are above the line',"Sentence",{html: "<center>Between 5 and 9 dots are above the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are above the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_red_square_above_.png'border='2'></center> ",q:'Between 5 and 9 dots are above the line.'}] ,
['2_BA_Filler-Target2_False_A_Baseline_X-X_X',"Sentence",{html: "<center>All dots are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All dots are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_green_triangle_below_.png'border='2'></center> ",q:'All dots are red.'}] ,
['2_BA_Filler-Target2_True_A_Baseline_X-X_X',"Sentence",{html: "<center>All dots are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All dots are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_red_square_above_.png'border='2'></center> ",q:'All dots are red.'}] ,
['2_BA_Target2_Target_A_Distributive_4-8_are above the line',"Sentence",{html: "<center>Between 4 and 8 dots are above the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 8 dots are above the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_red_triangle_above_.png'border='2'></center> ",q:'Between 4 and 8 dots are above the line.'}] ,
['2_BA_Target2_Target_A_Distributive_5-9_are above the line',"Sentence",{html: "<center>Between 5 and 9 dots are above the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are above the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_blue_square_above_.png'border='2'></center> ",q:'Between 5 and 9 dots are above the line.'}] ,
['2_BA_Target2_Target_A_Distributive_4-8_are below the line',"Sentence",{html: "<center>Between 4 and 8 dots are below the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 8 dots are below the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_green_triangle_below_.png'border='2'></center> ",q:'Between 4 and 8 dots are below the line.'}] ,
['2_BA_Target2_Target_A_Distributive_5-9_are below the line',"Sentence",{html: "<center>Between 5 and 9 dots are below the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are below the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_blue_square_below_.png'border='2'></center> ",q:'Between 5 and 9 dots are below the line.'}] ,
['2_BA_Filler-Target2_True_A_Baseline_X-X_X',"Sentence",{html: "<center>All dots are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All dots are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_green_triangle_above_.png'border='2'></center> ",q:'All dots are green.'}] ,
['2_BA_Filler-Target2_True_A_Baseline_X-X_X',"Sentence",{html: "<center>All dots are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All dots are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_dots_blue_square_above_.png'border='2'></center> ",q:'All dots are blue.'}] ,
['2_BA_Target2_Target_A_Distributive_4-8_are above the line',"Sentence",{html: "<center>Between 4 and 8 crosses are above the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 8 crosses are above the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_green_triangle_above_.png'border='2'></center> ",q:'Between 4 and 8 crosses are above the line.'}] ,
['2_BA_Target2_Target_A_Distributive_5-9_are below the line',"Sentence",{html: "<center>Between 5 and 9 crosses are below the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are below the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_red_square_below_.png'border='2'></center> ",q:'Between 5 and 9 crosses are below the line.'}] ,
['2_BA_Target2_Target_A_Distributive_4-8_are below the line',"Sentence",{html: "<center>Between 4 and 8 crosses are below the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 8 crosses are below the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_red_triangle_below_.png'border='2'></center> ",q:'Between 4 and 8 crosses are below the line.'}] ,
['2_BA_Target2_Target_A_Distributive_5-9_are above the line',"Sentence",{html: "<center>Between 5 and 9 crosses are above the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are above the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_green_square_above_.png'border='2'></center> ",q:'Between 5 and 9 crosses are above the line.'}] ,
['2_BA_Filler-Target2_False_B_Baseline_X-X_X',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_red_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Filler-Target2_True_B_Baseline_X-X_X',"Sentence",{html: "<center>All letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_green_.png'border='2'></center> ",q:'All letters are green.'}] ,
['2_BA_Target2_Target_A_Distributive_4-8_are above the line',"Sentence",{html: "<center>Between 4 and 8 crosses are above the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 8 crosses are above the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_red_triangle_above_.png'border='2'></center> ",q:'Between 4 and 8 crosses are above the line.'}] ,
['2_BA_Target2_Target_A_Distributive_5-9_are below the line',"Sentence",{html: "<center>Between 5 and 9 crosses are below the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are below the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_blue_square_below_.png'border='2'></center> ",q:'Between 5 and 9 crosses are below the line.'}] ,
['2_BA_Target2_Target_A_Distributive_4-8_are below the line',"Sentence",{html: "<center>Between 4 and 8 crosses are below the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 8 crosses are below the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_red_triangle_below_.png'border='2'></center> ",q:'Between 4 and 8 crosses are below the line.'}] ,
['2_BA_Target2_Target_A_Distributive_5-9_are below the line',"Sentence",{html: "<center>Between 5 and 9 crosses are below the line.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are below the line.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_A_crosses_blue_square_below_.png'border='2'></center> ",q:'Between 5 and 9 crosses are below the line.'}] ,
['2_BA_Filler-Target2_False_B_Baseline_X-X_X',"Sentence",{html: "<center>All letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_red_.png'border='2'></center> ",q:'All letters are blue.'}] ,
['2_BA_Filler-Target2_False_B_Baseline_X-X_X',"Sentence",{html: "<center>All letters are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>All letters are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/Target_B_crosses_blue_.png'border='2'></center> ",q:'All letters are red.'}] ,
['2_BA_Env-F_False_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_dots_blue_.png'border='2'></center> ",q:'Between 6 and 10 dots are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_dots_red_.png'border='2'></center> ",q:'Between 5 and 9 dots are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_dots_green_.png'border='2'></center> ",q:'Between 6 and 10 dots are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_dots_green_.png'border='2'></center> ",q:'Between 5 and 9 dots are connected to their letter.'}] ,
['2_BA_Filler-Env-F_True_A_Baseline_X-X_X',"Sentence",{html: "<center>Some dots are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some dots are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_A_dots_green_triangle_below_.png'border='2'></center> ",q:'Some dots are green.'}] ,
['2_BA_Filler-Env-F_True_A_Baseline_X-X_X',"Sentence",{html: "<center>Some dots are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some dots are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_A_dots_green_square_above_.png'border='2'></center> ",q:'Some dots are green.'}] ,
['2_BA_Env-F_False_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_dots_blue_.png'border='2'></center> ",q:'Between 6 and 10 dots are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_dots_blue_.png'border='2'></center> ",q:'Between 5 and 9 dots are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_dots_green_.png'border='2'></center> ",q:'Between 6 and 10 dots are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_dots_red_.png'border='2'></center> ",q:'Between 5 and 9 dots are connected to their letter.'}] ,
['2_BA_Filler-Env-F_True_A_Baseline_X-X_X',"Sentence",{html: "<center>Some dots are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some dots are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_A_dots_green_triangle_above_.png'border='2'></center> ",q:'Some dots are green.'}] ,
['2_BA_Filler-Env-F_True_A_Baseline_X-X_X',"Sentence",{html: "<center>Some dots are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some dots are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_A_dots_red_square_above_.png'border='2'></center> ",q:'Some dots are red.'}] ,
['2_BA_Env-F_False_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_blue_.png'border='2'></center> ",q:'Between 6 and 10 crosses are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_green_.png'border='2'></center> ",q:'Between 5 and 9 crosses are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_green_.png'border='2'></center> ",q:'Between 6 and 10 crosses are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_red_.png'border='2'></center> ",q:'Between 5 and 9 crosses are connected to their letter.'}] ,
['2_BA_Filler-Env-F_True_B_Baseline_X-X_X',"Sentence",{html: "<center>Some letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_green_.png'border='2'></center> ",q:'Some letters are green.'}] ,
['2_BA_Filler-Env-F_True_B_Baseline_X-X_X',"Sentence",{html: "<center>Some letters are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some letters are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_red_.png'border='2'></center> ",q:'Some letters are red.'}] ,
['2_BA_Env-F_False_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_red_.png'border='2'></center> ",q:'Between 6 and 10 crosses are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_blue_.png'border='2'></center> ",q:'Between 5 and 9 crosses are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_blue_.png'border='2'></center> ",q:'Between 6 and 10 crosses are connected to their letter.'}] ,
['2_BA_Env-F_False_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_blue_.png'border='2'></center> ",q:'Between 5 and 9 crosses are connected to their letter.'}] ,
['2_BA_Filler-Env-F_True_B_Baseline_X-X_X',"Sentence",{html: "<center>Some letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_blue_.png'border='2'></center> ",q:'Some letters are blue.'}] ,
['2_BA_Filler-Env-F_True_B_Baseline_X-X_X',"Sentence",{html: "<center>Some letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/False_B_crosses_blue_.png'border='2'></center> ",q:'Some letters are blue.'}] ,
['2_BA_Env-T_True_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_green_.png'border='2'></center> ",q:'Between 6 and 10 dots are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_blue_.png'border='2'></center> ",q:'Between 5 and 9 dots are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_red_.png'border='2'></center> ",q:'Between 6 and 10 dots are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_blue_.png'border='2'></center> ",q:'Between 5 and 9 dots are connected to their letter.'}] ,
['2_BA_Filler-Env-T_False_A_Baseline_X-X_X',"Sentence",{html: "<center>Some dots are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some dots are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_A_dots_red_triangle_above_.png'border='2'></center> ",q:'Some dots are green.'}] ,
['2_BA_Filler-Env-T_False_A_Baseline_X-X_X',"Sentence",{html: "<center>Some dots are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some dots are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_A_dots_blue_square_above_.png'border='2'></center> ",q:'Some dots are green.'}] ,
['2_BA_Env-T_True_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_green_.png'border='2'></center> ",q:'Between 6 and 10 dots are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_red_.png'border='2'></center> ",q:'Between 5 and 9 dots are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_green_.png'border='2'></center> ",q:'Between 6 and 10 dots are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 dots are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 dots are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_blue_.png'border='2'></center> ",q:'Between 5 and 9 dots are connected to their letter.'}] ,
['2_BA_Filler-Env-T_False_B_Baseline_X-X_X',"Sentence",{html: "<center>Some letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_green_.png'border='2'></center> ",q:'Some letters are blue.'}] ,
['2_BA_Filler-Env-T_False_B_Baseline_X-X_X',"Sentence",{html: "<center>Some letters are green.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some letters are green.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_dots_blue_.png'border='2'></center> ",q:'Some letters are green.'}] ,
['2_BA_Env-T_True_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_red_.png'border='2'></center> ",q:'Between 6 and 10 crosses are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_red_.png'border='2'></center> ",q:'Between 5 and 9 crosses are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_blue_.png'border='2'></center> ",q:'Between 6 and 10 crosses are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_green_.png'border='2'></center> ",q:'Between 5 and 9 crosses are connected to their letter.'}] ,
['2_BA_Filler-Env-T_False_B_Baseline_X-X_X',"Sentence",{html: "<center>Some letters are red.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some letters are red.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_blue_.png'border='2'></center> ",q:'Some letters are red.'}] ,
['2_BA_Filler-Env-T_False_B_Baseline_X-X_X',"Sentence",{html: "<center>Some letters are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some letters are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_green_.png'border='2'></center> ",q:'Some letters are blue.'}] ,
['2_BA_Env-T_True_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_green_.png'border='2'></center> ",q:'Between 6 and 10 crosses are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_red_.png'border='2'></center> ",q:'Between 5 and 9 crosses are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_6-10_are connected to their letter',"Sentence",{html: "<center>Between 6 and 10 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 6 and 10 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_green_.png'border='2'></center> ",q:'Between 6 and 10 crosses are connected to their letter.'}] ,
['2_BA_Env-T_True_B_Distributive_5-9_are connected to their letter',"Sentence",{html: "<center>Between 5 and 9 crosses are connected to their letter.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 9 crosses are connected to their letter.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_B_crosses_red_.png'border='2'></center> ",q:'Between 5 and 9 crosses are connected to their letter.'}] ,
['2_BA_Filler-Env-T_False_A_Baseline_X-X_X',"Sentence",{html: "<center>Some crosses are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some crosses are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_A_crosses_green_triangle_above_.png'border='2'></center> ",q:'Some crosses are blue.'}] ,
['2_BA_Filler-Env-T_False_A_Baseline_X-X_X',"Sentence",{html: "<center>Some crosses are blue.</center><br> <center> <canvas id='myCanvas' width='220' height='210'></canvas></center>"},"SubHtmlFlash",{html:"<center>Some crosses are blue.</center> <br><center> <img src='http://cogexpe.scicog.fr/PSIM/Non-Max/True_A_crosses_red_square_above_.png'border='2'></center> ",q:'Some crosses are blue.'}] ,

    ["quest", "NewForm", {html:{include: 'questionary.html'}}],
    ["sr", "__SendResults__", { }],
    ["code", "Code", {html: "<h2> Code </h2><br>" + generateRandomNumber()}],


];
