var shuffleSequence =  seq("agreement","instr", "practice", randomize(shuffle(startsWith('T'), startsWith('F'), startsWith('E'))),"quest","sr","code")

var showProgressBar = false;

var pageTitle= "Model_2";

function generateRandomNumber(){
    var num = Math.floor(Math.random()*58+40);
    var myArray = ['R', 'S', 'X', 'U','V'];
    var rand = myArray[Math.floor(Math.random() * myArray.length)];
    var myArray2 = ['I', 'O', 'E', 'U'];
    var rand2 = myArray2[Math.floor(Math.random() * myArray2.length)];
    var myArray3 = ['Y', 'Z', 'W'];
    var rand3 = myArray3[Math.floor(Math.random() * myArray3.length)];
    var num2 = Math.floor(Math.random()*6+1);

    var n = String(rand)+String(num)+String(rand3)+String(num2)+String(rand2);

return n;
}

var manualSendResults = true;
var defaults = [
    "Question", {hasCorrect: true},
    "Message", {hideProgressBar: true},
    "Sentence", {hideProgressBar: true, transfer: 2000},
    "Form", {hideProgressBar: true,continueOnReturn: true,saveReactionTime: true},
    "NewForm", {hideProgressBar: true,continueOnReturn: true,saveReactionTime: true},
    "PictureAccept", {presentAsScale: true,hideProgressBar: true},
    "SubHtmlFlash", {presentAsScale: true, presentHorizontally: false, as: ["True", "False"]},
    "Code", {hideProgressBar: true,transfer: null}];


var items = [
    ['agreement', "NewForm", {html: {include: 'agreement_EN.html'}}],
    ['instr',"NewMessage", {html: {include: 'instructions.html'}}],

    ['practice', "Sentence", {html: "<center>Some dots are blue.</center> <br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'> </center>"},
     "SubHtmlFlash", {html:"<center>Some dots are blue.</center> <br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_A_dots_blue_square_below_.png' border='2'></center>", q:"Practice"}],

    ['Target1_False_A_Baseline',"Sentence",{html: "<center>The dots are blue.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>The dots are blue.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_green_Square_below_.png'border='2'></center> ",q:'Target1_False_A_Baseline'}] ,
    ['Target1_True_A_Baseline',"Sentence",{html: "<center>The dots are green.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>The dots are green.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_green_Triangle_above_.png'border='2'></center> ",q:'Target1_True_A_Baseline'}] ,
 
    ['Filler-Target1_True_A_Baseline',"Sentence",{html: "<center>All dots are red.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All dots are red.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_red_Triangle_below_.png'border='2'></center> ",q:'Filler-Target1_True_A_Baseline'}] ,
    ['Filler-Target1_True_A_Baseline',"Sentence",{html: "<center>All dots are orange.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All dots are orange.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_orange_Square_above_.png'border='2'></center> ",q:'Filler-Target1_True_A_Baseline'}] ,
  
    ['Filler-Target1_False_B_Baseline',"Sentence",{html: "<center>All letters are orange.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All letters are orange.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_blue_.png'border='2'></center> ",q:'Filler-Target1_False_B_Baseline'}] ,
    ['Filler-Target1_True_B_Baseline',"Sentence",{html: "<center>All letters are orange.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All letters are orange.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_orange_.png'border='2'></center> ",q:'Filler-Target1_True_B_Baseline'}] ,
  
    ['Target1_False_A_Baseline',"Sentence",{html: "<center>The crosses are blue.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>The crosses are blue.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_crosses_green_Square_below_.png'border='2'></center> ",q:'Target1_False_A_Baseline'}] ,
    ['Target1_True_A_Baseline',"Sentence",{html: "<center>The crosses are orange.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>The crosses are orange.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_crosses_orange_Triangle_above_.png'border='2'></center> ",q:'Target1_True_A_Baseline'}] ,
  
    ['Target2_Target_B_Collective',"Sentence",{html: "<center>Between 5 and 12 dots surround their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots surround their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_green_.png'border='2'></center> ",q:'Target2_Target_B_Collective'}] ,
    ['Target2_Target_B_Collective',"Sentence",{html: "<center>Between 5 and 10 dots surround their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 10 dots surround their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_green_.png'border='2'></center> ",q:'Target2_Target_B_Collective'}] ,
  
    ['Filler-Target2_False_A_Baseline',"Sentence",{html: "<center>All dots are blue.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All dots are blue.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_green_Triangle_above_.png'border='2'></center> ",q:'Filler-Target2_False_A_Baseline'}] ,
    ['Filler-Target2_False_A_Baseline',"Sentence",{html: "<center>All dots are blue.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All dots are blue.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_orange_Square_above_.png'border='2'></center> ",q:'Filler-Target2_False_A_Baseline'}] ,
  
    ['Env-F_False_A_Collective',"Sentence",{html: "<center>Between 5 and 12 dots form a square.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots form a square.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_A_dots_orange_Square_above_.png'border='2'></center> ",q:'Env-F_False_A_Collective'}] ,
    ['Env-F_False_A_Collective',"Sentence",{html: "<center>Between 4 and 10 dots form a triangle.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 10 dots form a triangle.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_A_dots_red_Triangle_below_.png'border='2'></center> ",q:'Env-F_False_A_Collective'}] ,
  
    ['Filler-Env-F_True_B_Baseline',"Sentence",{html: "<center>Some letters are red.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Some letters are red.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_B_dots_red_.png'border='2'></center> ",q:'Filler-Env-F_True_B_Baseline'}] ,
    ['Filler-Env-F_True_B_Baseline',"Sentence",{html: "<center>Some letters are orange.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Some letters are orange.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_B_dots_orange_.png'border='2'></center> ",q:'Filler-Env-F_True_B_Baseline'}] ,
  
    ['Env-T_True_A_Collective',"Sentence",{html: "<center>Between 5 and 12 dots form a square.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots form a square.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_orange_Square_below_.png'border='2'></center> ",q:'Env-T_True_A_Collective'}] ,
    ['Env-T_True_A_Collective',"Sentence",{html: "<center>Between 4 and 10 dots form a triangle.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 10 dots form a triangle.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_red_Triangle_below_.png'border='2'></center> ",q:'Env-T_True_A_Collective'}] ,
  
    ['Filler-Env-T_False_A_Baseline',"Sentence",{html: "<center>Some dots are red.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Some dots are red.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_blue_Triangle_below_.png'border='2'></center> ",q:'Filler-Env-T_False_A_Baseline'}] ,
    ['Filler-Env-T_False_A_Baseline',"Sentence",{html: "<center>Some dots are blue.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Some dots are blue.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_orange_Square_below_.png'border='2'></center> ",q:'Filler-Env-T_False_A_Baseline'}] ,
  
    ['Env-T_True_A_Collective',"Sentence",{html: "<center>Between 5 and 12 crosses form a square.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 crosses form a square.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_crosses_red_Square_below_.png'border='2'></center> ",q:'Env-T_True_A_Collective'}] ,
    ['Env-T_True_A_Collective',"Sentence",{html: "<center>Between 4 and 10 crosses form a triangle.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 10 crosses form a triangle.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_crosses_green_Triangle_below_.png'border='2'></center> ",q:'Env-T_True_A_Collective'}] ,
  
    
    ['Target1_False_B_Baseline',"Sentence",{html: "<center>The letters are green.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>The letters are green.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_red_.png'border='2'></center> ",q:'Target1_False_B_Baseline'}] ,
    ['Target1_True_B_Baseline',"Sentence",{html: "<center>The letters are green.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>The letters are green.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_green_.png'border='2'></center> ",q:'Target1_True_B_Baseline'}] ,
   
    ['Filler-Target1_False_B_Baseline',"Sentence",{html: "<center>All letters are green.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_blue_.png'border='2'></center> ",q:'Filler-Target1_False_B_Baseline'}] ,
    ['Filler-Target1_False_B_Baseline',"Sentence",{html: "<center>All letters are green.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_orange_.png'border='2'></center> ",q:'Filler-Target1_False_B_Baseline'}] ,
   
    ['Target2_Target_A_Collective',"Sentence",{html: "<center>Between 5 and 12 dots form a square.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots form a square.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_blue_Square_below_.png'border='2'></center> ",q:'Target2_Target_A_Collective'}] ,
    ['Target2_Target_A_Collective',"Sentence",{html: "<center>Between 4 and 10 dots form a triangle.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 10 dots form a triangle.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_red_Triangle_above_.png'border='2'></center> ",q:'Target2_Target_A_Collective'}] ,
   
    ['Filler-Target2_True_B_Baseline',"Sentence",{html: "<center>All letters are green.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All letters are green.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_green_.png'border='2'></center> ",q:'Filler-Target2_True_B_Baseline'}] ,
    ['Filler-Target2_False_B_Baseline',"Sentence",{html: "<center>All letters are red.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>All letters are red.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_green_.png'border='2'></center> ",q:'Filler-Target2_False_B_Baseline'}] ,
   
    ['Env-F_False_B_Collective',"Sentence",{html: "<center>Between 5 and 12 dots surround their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots surround their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_B_dots_blue_.png'border='2'></center> ",q:'Env-F_False_B_Collective'}] ,
    ['Env-F_False_B_Collective',"Sentence",{html: "<center>Between 5 and 12 dots surround their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots surround their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_B_dots_red_.png'border='2'></center> ",q:'Env-F_False_B_Collective'}] ,
    
    ['Env-T_True_B_Collective',"Sentence",{html: "<center>Between 5 and 12 dots surround their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots surround their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_B_dots_orange_.png'border='2'></center> ",q:'Env-T_True_B_Collective'}] ,
    ['Env-T_True_B_Collective',"Sentence",{html: "<center>Between 5 and 10 dots surround their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 10 dots surround their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_B_dots_green_.png'border='2'></center> ",q:'Env-T_True_B_Collective'}] ,
   
    ['Filler-Env-T_False_A_Baseline',"Sentence",{html: "<center>Some dots are green.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Some dots are green.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_orange_Triangle_below_.png'border='2'></center> ",q:'Filler-Env-T_False_A_Baseline'}] ,
    ['Filler-Env-T_False_A_Baseline',"Sentence",{html: "<center>Some dots are red.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Some dots are red.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_blue_Square_below_.png'border='2'></center> ",q:'Filler-Env-T_False_A_Baseline'}] ,
   
    ['Target2_Target_B_Distributive',"Sentence",{html: "<center>Between 5 and 12 dots are connected to their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots are connected to their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_green_.png'border='2'></center> ",q:'Target2_Target_B_Distributive'}] ,
    ['Target2_Target_B_Distributive',"Sentence",{html: "<center>Between 5 and 10 dots are connected to their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 10 dots are connected to their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_blue_.png'border='2'></center> ",q:'Target2_Target_B_Distributive'}] ,

    ['Target2_Target_B_Distributive',"Sentence",{html: "<center>Between 5 and 12 dots are connected to their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots are connected to their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_red_.png'border='2'></center> ",q:'Target2_Target_B_Distributive'}] ,
    ['Target2_Target_B_Distributive',"Sentence",{html: "<center>Between 5 and 10 dots are connected to their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 10 dots are connected to their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_B_dots_blue_.png'border='2'></center> ",q:'Target2_Target_B_Distributive'}] ,

    ['Env-F_False_A_Distributive',"Sentence",{html: "<center>Between 5 and 12 dots are above the line.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots are above the line.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_A_dots_blue_Square_above_.png'border='2'></center> ",q:'Env-F_False_A_Distributive'}] ,
    ['Env-F_False_A_Distributive',"Sentence",{html: "<center>Between 4 and 10 dots are above the line.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 10 dots are above the line.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_A_dots_orange_Triangle_above_.png'border='2'></center> ",q:'Env-F_False_A_Distributive'}] ,

    ['Env-T_True_A_Distributive',"Sentence",{html: "<center>Between 5 and 12 dots are below the line.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots are below the line.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_green_Square_below_.png'border='2'></center> ",q:'Env-T_True_A_Distributive'}] ,
    ['Env-T_True_A_Distributive',"Sentence",{html: "<center>Between 4 and 10 dots are below the line.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 10 dots are below the line.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_orange_Triangle_below_.png'border='2'></center> ",q:'Env-T_True_A_Distributive'}] ,

    ['Env-T_True_A_Distributive',"Sentence",{html: "<center>Between 5 and 12 dots are above the line.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots are above the line.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_orange_Square_above_.png'border='2'></center> ",q:'Env-T_True_A_Distributive'}] ,
    ['Env-T_True_A_Distributive',"Sentence",{html: "<center>Between 4 and 10 dots are above the line.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 10 dots are above the line.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_A_dots_red_Triangle_above_.png'border='2'></center> ",q:'Env-T_True_A_Distributive'}] ,

    ['Target2_Target_A_Distributive',"Sentence",{html: "<center>Between 5 and 12 dots are below the line.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots are below the line.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_blue_Square_below_.png'border='2'></center> ",q:'Target2_Target_A_Distributive'}] ,
    ['Target2_Target_A_Distributive',"Sentence",{html: "<center>Between 4 and 10 dots are below the line.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 4 and 10 dots are below the line.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/Target_A_dots_red_Triangle_below_.png'border='2'></center> ",q:'Target2_Target_A_Distributive'}] ,

    ['Env-F_False_B_Distributive',"Sentence",{html: "<center>Between 5 and 12 dots are connected to their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots are connected to their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_B_dots_green_.png'border='2'></center> ",q:'Env-F_False_B_Distributive'}] ,
    ['Env-F_False_B_Distributive',"Sentence",{html: "<center>Between 5 and 10 dots are connected to their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 10 dots are connected to their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/False_B_dots_orange_.png'border='2'></center> ",q:'Env-F_False_B_Distributive'}] ,
 
    ['Env-T_True_B_Distributive',"Sentence",{html: "<center>Between 5 and 12 dots are connected to their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 12 dots are connected to their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_B_dots_blue_.png'border='2'></center> ",q:'Env-T_True_B_Distributive'}] ,
    ['Env-T_True_B_Distributive',"Sentence",{html: "<center>Between 5 and 10 dots are connected to their letter.</center><br> <center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/white.png' border='2'></center>"},"SubHtmlFlash",{html:"<center>Between 5 and 10 dots are connected to their letter.</center> <br><center> <img src='https://dl.dropboxusercontent.com/u/13340774/Images/True_B_dots_blue_.png'border='2'></center> ",q:'Env-T_True_B_Distributive'}] ,
 
    ["quest", "NewForm", {html:{include: 'questionary.html'}}],
    ["sr", "__SendResults__", { }],
    ["code", "Code", {html: "<h2> Code </h2><br>" + generateRandomNumber()}],


];
